### ISSUE TITLE
Black Screen On Startup

### ISSUE THREAD

**Issue by cow-killer** [drauger-os-development/steam-login-session#1]
Black screen when trying to launch Steam Big Picture mode from the login screen.

**Comment by l0nkDev** [comment]
same issue, i get a black screen for a second, then it kicks me back to the login screen

**Comment by Batcastle** [comment]
Sorry I am just now getting to this guys! 

I had a user on Telegram report that running `steam-de` as root in a TTY gets it to work. So, with that knowledge, commits efe65f8097a74ed5b7272c2bb72a444b9fe93713 and f75d9a018317cf0110195eddfecec5f207acebcd are intended to pair things down to the bare essentials and get things working. Other bugs can be fixed later, although I doubt there will be many (famous last words!).

**Comment by Batcastle** [comment]
Since I haven't heard any issues around this, and have seen it working, I will close this issue. If there are further issues related to this, please open a new issue report, referencing this one.
